title: EgoLife XR Lifelogging
description: WebXR 기반 1인칭 멀티모달 라이프로깅 데모
theme: minima
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
google_analytics: ""
